# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rx-networking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rx-networking
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'SnapKit'
  pod 'Nuke'

end
